### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by nitun** [devgujar/Assignment#2]
missing type BiffException
for this line:

//Get Test data
		Hashtable<String, String> excellData =rtmediaPage.GetExcell_Data_As_Hashtable("TC001_Verify_Sigup_on_rtMedia_NewUser.xls");

which is fetching excel data.

**Comment by pm-devanand-gujar** [comment]
I am looking into this and will revert back by tomorrow EOD.

**Comment by pm-devanand-gujar** [comment]
I am using JExcelApi for reading data from excel.
I missed out to add relative path for jxl.jar file.
updated .classpath project file with the relative path to jxl.jar.

Please take an update. This issue should be resolved now.

**Comment by nitun** [comment]
Thanks. it working now.
